---
title: Kyle Tress
timezone: UTC
collections:
  newsletters:
    title: Newsletters
    output: true
  posts:
    title: Posts
    output: true
  reading:
    title: Reading
    output: true
  uploads:
    title: Uploads
    output: true
email: kyle@kyletress.com
description: The website of 2014 Olympian Kyle Tress
url: https://kyletress.github.io
locale: en
markdown: kramdown
permalink: "/:title"
quote: Mens sana in corpore sano
exclude:
- LICENSE
- README.md
- Gemfile
- Gemfile.lock
defaults:
  -
    scope:
      path: "" # all files
      type: "posts"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
