---
title: Kyle Tress
timezone: UTC
email: kyle@kyletress.com
description: The website of 2014 Olympian Kyle Tress
url: https://kyletress.github.io
locale: en
markdown: kramdown
kramdown:
  auto_ids: false
permalink: "/:title"
exclude:
- LICENSE
- README.md
- Gemfile
- Gemfile.lock
