# Site settings
title: Kyle Tress
email: kyle@kyletress.com
description: The website of 2014 Olympian Kyle Tress
url: "https://kyletress.github.io" 
locale: "en"

# Build settings
markdown: kramdown
permalink: /:title

# Files
exclude:
  - LICENSE
  - README.md
  - Gemfile
  - Gemfile.lock
