# Site settings
title: Skeleton
email: your-email@domain.com
description: "The Skeleton Jekyll theme"
url: "http://yourdomain.com" # the base hostname & protocol for your site
locale: "en"

# Build settings
markdown: kramdown
permalink: /:title

# Files
exclude:
  - LICENSE
  - README.md
  - Gemfile
  - Gemfile.lock
