---
title: Kyle Tress
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
  faqs:
    title: Faqs
    output: false 
email: kyle@kyletress.com
description: The website of 2014 Olympian Kyle Tress
url: https://kyletress.github.io
locale: en
markdown: kramdown
kramdown:
  auto_ids: false
permalink: "/:title"
show-social-links-in-footer: true
show-share-buttons: true
site-quote: Mens sana in corpore sano
disqus-shortname: kyletress

# Files
include:
- _pages
exclude:
- LICENSE
- README.md
- Gemfile
- Gemfile.lock

# Defaults
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
